### ISSUE TITLE
GRIP move Robot when you see blob

### ISSUE THREAD

**Issue by SagesOfRPG** [newheights/frc5902-testbed-gitenabled#8]
Generate some GRIP code to have the robot move forward when it sees a "blob". Seems that the fuel balls work ok as a blob so maybe we can use them?

**Comment by RobotGeissler** [comment]
Made a Network Table connection that measures the contours, we can reference it for commands and subsystems to design a function for the GRIP input.

**Comment by SagesOfRPG** [comment]
Not this year! Looking at Pixy camera for vision.
